### PR TITLE
Fix zoom

### PR DESCRIPTION
**Pull request by mdeweerd**
Zooming did not seem to work, I set to 5, 10 or 20, the result was the same.

This fixes it for me.

Also bumped the version, required by KiBot - probably a checkin that was not pushed or so.

### CODE REVIEW

**Comment by set-soft** [comment]
I don't like this. In fact I had problems doing exactly this.

You can't send tons of events that takes an unknown time to complete, they can be lost.

This is lamentable, but real. If the drawing is very slow and you keep sending events some of them will be discarded. This is why I'm checking if KiCad is responsive before sending more events. 

If my mechanism is failing in your setup we must figure out why, not remove the check.

**Comment by mdeweerd** [comment]
When I tested the zooming "interactively" using the xdotool from the cmdline, this worked better than sending them separately where I lost virtual mouse events.

For other events one has to wait, but for zooming it was better.  Interactively (slower) we could see that the current rendering is not completed when another zoom level is added.

Apparently you have the opposite experience with the zooming.

This is lauched in the docker VM.

What do you propose to identify the cause?  I think that the video capture is not giving enough info.

**Comment by mdeweerd** [comment]
With the fix I had a full width image, without it, I have this:
image

**Comment by mdeweerd** [comment]
I changed the code to:
```
             zoom = -zoom
             zoom_b = '5'
         for _ in range(zoom):
+            sleep(1)
             xdotool(['click', zoom_b])
+            sleep(1)
             wait_3d_ready()
```

Adding the lower sleep (first) did not help, the sleep before the xdotool/click helped.

I am sending you a private message with a link to the videos and the outputs on our common domain.

**Comment by set-soft** [comment]
> I am sending you a private message with a link to the videos and the outputs on our common domain.

My ieee redirector isn't working, please send it to other of my accounts.

**Pull request closed without merging**
